snellServer:
  image:
    registry: ghcr.io
    repository: xudongcc/snell-server
    tag: 5.0.1
    pullPolicy: IfNotPresent
    pullSecrets: []

  resourcesPreset: "micro"
  resources: {}

  host: "::1"
  port: 6333
  psk: "changeme"

shadowTLS:
  enabled: true
  image:
    registry: ghcr.io
    repository: ihciah/shadow-tls
    tag: v0.2.25
    pullPolicy: IfNotPresent
    pullSecrets: []

  resourcesPreset: "micro"
  resources: {}

  port: 8443
  listenHost: "::0"
  serverHost: "::1"
  fastOpen: "1"
  sni: "gateway.icloud.com"
  password: "changeme"

hostNetwork: true

dnsPolicy: Default

service:
  enabled: true
  exposeSnellServer: false
  type: ClusterIP
  annotations: {}
  labels: {}
  clusterIP: ""
  internalTrafficPolicy: Local
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  sessionAffinityConfig: {}
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  extraPorts: []

traefik:
  ingressRouteTCP:
    enabled: true
    name: ""
    annotations: {}
    labels: {}
    entryPoints:
      - websecure
    nativeLB: true
    tls:
      passthrough: true

nodeSelector: {}

tolerations: []

commonLabels: {}

commonAnnotations: {}

podLabels: {}

podAnnotations: {}
